source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'rails', '~> 7.0.0'
gem 'sqlite3'
gem 'administrate', '~> 0.17.0'
gem 'administrate_filterable', path: File.path('../../')

group :development, :test do
  gem 'rb-readline'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 3.8'
end
